#+title: Todo

- [X] OPTIMIZATION: do all the draws at the same time. requires adding back vertex
 colors and a bit of refactoring.
  - [X] draw queue with consecutive poly and circle draw calls grouped together so
    that they can be batch drawn together. use instancing for grouped circles
- [X] poly circles as new function / optional
- [X] cache projection matrix
- [X] cull off screen world draws
- [X] Logging system, that can log to stdout/stderr (like env_logger), or to an
  onscreen thingy.
- [X] functions to change speed of physics time
- [X] FIX: if you render too much text it just gives up and stops rendering any
  more text, but just for that one draw queue
  - no more textures are drawn, not just ones from the same texture atlas. nothing.
- [ ] ui multiline text
- [ ] ui text wrapping
- [ ] ui scroll culling (?)
- [ ] easier physics
- [ ] proper sound
- [ ] something is broken evident in shapes_3d example
- [ ] sphere SDF
- [ ] you should be able to delete textures and images and stuff
- [ ] text example is broken
- [ ] rounded rectangle primitive
  https://www.shadertoy.com/view/Nlc3zf
  https://www.youtube.com/watch?v=62-pRVZuS5c
  https://www.youtube.com/watch?v=s5NGeUV2EyU
  #+begin_src glsl
float box(vec2 position, vec2 halfSize, float cornerRadius) {
   position = abs(position) - halfSize + cornerRadius;
   return length(max(position, 0.0)) + min(max(position.x, position.y), 0.0) - cornerRadius;
}

vec4 drawBox(vec2 center, vec2 size, float cornerRadius, vec4 color, vec2 fragCoord) {
    vec2 position = (2.0 * (fragCoord - center) - iResolution.xy) / iResolution.y;
    vec2 halfSize = size / 2.0;
    float d = box(position, halfSize, cornerRadius);

    return vec4(1.0) - vec4(sign(d)) * color;
}

void mainImage(out vec4 fragColor, in vec2 fragCoord) {
    vec2 center = vec2(100.0, 0.0);
    vec2 size = vec2(1.0, 0.5);
    float cornerRadius = 0.2; // clamp to between 0 and (shortest side length / 2)
	fragColor = drawBox(center, size, cornerRadius, vec4(1.0, 1.0, 1.0, 1.0), fragCoord);
}

  #+end_src
- [ ] probably split into multiple crates
- [ ] now we have logging. log things
- [ ] SI Unit system
- [ ] clipping/masking
- [ ] drop shadows 2d
- [X] Reduce build time
- [ ] fix culling
- [ ] cull glyph textures out of view
- [ ] test transform 2 and 3D
- [ ] Unity particle system
- [ ] screen shake
- [ ] Compute shaders.
- [X] frame time in debug
- [ ] color schemes? like built in struct called colour scheme with gruvbox and
  cattpucin and stuff?
- [X] Fix examples now get_input() doesnt exist SPC / get_input
- [ ] use bump allocators for per-frame data that gets cleared
- [X] texture atlasses
- [ ] clipboard interaction
- [ ] Serde feature to make everything publicly facing serializable.
  - [ ] automatic saving and loading support with efficient binary format
- [X] Transparency is fucked
  - [X] Very fucked
  - [X] Someone needs to do something about this
- [ ] debug AABB draw lines on ::new() in wireframe feature
- [ ] draw line 3D
- [ ] draw Sphere
- [X] draw cube
- [ ] draw cuboid from Vec3
- [ ] like retaining 2d shape state would be pretty efficient ngl
  - maybe dont have to do culling every frame, like every 5 frames or something.
    zoo wee mama!!!
- [ ] match material HashMap<Material, Mesh>
- [ ] Circle anti aliasing between outline and fill is non existent
- [X] Move draw param overrides to the material
- [X] https://github.com/sqrew/tunes
- [ ] Dithering to reduce colour banding
- [ ] Signed distance field / https://raytracing.github.io/books/RayTracingInOneWeekend.html
- [X] Custom materials
- [X] Custom programs
- [X] Post processing [7/7]
  - [X] Bloom
  - [X] Pixelate
    - [X] Would be nice if this actually made it render less pixels but we may
      just need to advise people to use the custom texture rendering method
      below if they care about performance. (documentation!!!)
  - [X] Saturation
  - [X] Hue rotate
  - [X] Brightness
  - [X] Vignette
  - [X] Sharpen?
- [X] finish drawing circle outlines and add support for elipsis and arcs, this can all be one shader if you try hard enough.
- [X] Render to custom texture
  - [X] Create new render pipeline
    - [X] Should be refactored into it's own struct
    - [X] Contains all render queues + some sort of output descriptor
      - [X] May need refactoring for camera's and stuff to use the custom output size
  - [X] Let you use the texture however, like render it to the screen or use it in
    a compute shader like for game of life.
    - [X] Or render to a lower resolution texture and scale it up for a pixelated effect.
- [X] draw hexagon poly thing
- [ ] arbritrary rotation and custom material for all 2d shapes
- [X] good api for creating and managing and drawing spritesheets
- [-] TEXT RENDERING!!!
  - [X] fonts
  - [X] multiline
  - [ ] layout / text wrapping / text alignment
  - [X] rich text
  - [X] text measurement
  - [ ] text scale and rotation
  - [ ] sdf?
  - [ ] 3d
- [X] transparant textures?
- [-] controller support
  - [X] Implementation
  - [ ] Testing
  - [ ] Examples
- [ ] drag and drop files?
- [-] Animation support
  - [X] Needs some sort of retained state.
  - [X] Maybe generic over types that implement some trait.
    - [X] Implement for all numerics, transform3D, colour, vectors.
  - [X] Struct contains start, end, time, and interpolation function.
  - [X] Interpolation function trait.
    - [X] So you could have structs with configurable interpolation.
  - [ ] sprite animation
    - (needs spritesheets/atlasses) ✅
  - [ ] maybe have my own proc-macro based compiler to turn a folder of sprites
    into a sprite sheet, indexable by a perfect &'static str hash table
    - [ ] would be nice to also have a type safe enum based approach, idk how i'd
      do that though. automatically generate the enum from the file names,
      converted to camel case? that would certainly be nice, and you'd get
      compiler errors when you update the name of one of the files or remove a sprite.
  - [ ] https://docs.rs/macroquad/latest/macroquad/experimental/animation/index.html
  - [ ] Animation state machine
  - [ ] pause animation controller
- [ ] egui_dock
- [X] winit input helper fork add precise mouse movemnt so that i can have all the
  positions of it in the paint program for better curves
- [ ] image texture pair struct with builtin methods and maybe a `dirty`
- [ ] make implementing ui like clicking and hovering easier
- [ ] software: draw thick line function for circles or something, see if instancing circles is good enough
- [ ] hardware: rounded line function (with circle end caps). can replace a bunch of boiler plate in api.rs
- [X] expose egui charts if not already
- [ ] let users access intermediary depth textures only if they want it
- [X] impl mul TransformXD for VecX
- [X] impl mul Transform * Transform
- [X] .translate_point method
- [X] area perimiter methods on shapes
- [X] draw line through many points (path)
- [X] Macros for all this *Ref stuff
- [X] draw text
  - [X] draw_fps function
- [X] 2d mouse camera controller, like whats in the examples but built into the engine
- [X] Custom keybind/action map struct generic over action enum/struct
- [X] https://docs.rs/macroquad/latest/macroquad/experimental/collections/storage/index.html
- [ ] multiple cameras outputting to textures
  - [ ] maybe a use_cameras function
- [X] Render pass
  #+begin_src rust
    pub struct RenderPass {
        pub color_texture: Texture2D,
        pub depth_texture: Option<Texture2D>,
        pub(crate) render_pass: Arc<miniquad::RenderPass>,
    }
    #+end_src
  - [X] we need a function for creating an empty texture and one for creating a render pass from existing textures or just a resolution
  - [X] function to render a texture to the screen as a fullscreen quad
  - [X] just let the user create a render pipeline which has the various draw queues, and let the draw queues also contain their proj matrices so it can be drawn with just a reference to the engine state.
  - [X] let the engine use a default render pipeline, and have it be a vector of impl RenderPipelinePass which is implemented by draw_queue 2 and 3d and for drawing the UI in case the user wants to put things above that.
  this should make it possible to add post processing effects easily
- [ ] drawing curves
  - [ ] lines that connect points
  - [ ] bezier
  - [ ] cubic
  - [ ] quadratic
- [ ] Documentation
- [ ] arcs/slices of circles
- [ ] rounded rectangles
- [ ] splines
- [ ] 2d grid
- [X] function to get screen size, width, height
- [ ] Fix backface culling
- [ ] export all colours as normal consts
- [ ] Transform example
- [ ] change cursor icons
- [ ] Reorganize everything
  Especially draw_queue2d.rs and shapes2d.rs
- [ ] test colours
- [ ] test everything
- [ ] 2D custom materials
  - [ ] use_material & use_default_material functions
  - [ ] add default 2d material to render pipeline
  - [ ] hashmap of material ref to mesh
- [ ] https://github.com/not-fl3/macroquad/blob/master/examples/screen_texture.rs
- [ ] better 2D physics. platformer
- [ ] is this ECS?
  - [ ] this could totally work lets be REAL https://docs.rs/hecs/latest/hecs/
- [ ] lua scripting support
- [X] replace anyhow with concrete error types
- [X] more warnings and better errors
- [X] Colors from hex code
- [X] Custom 3D material example
- [X] Batch textures
- [-] Arbritrary transform of 2D shapes
  - [X] Transform2D struct
  - [ ] functions to specify arbritrary transform of 2d shapes
- [ ] 2D & 3D wireframe mode. automatic. can disregard material (maybe? vertex shaders?)
- [ ] Memory/GPU profiler
- [ ] Asset packing
  - [ ] and loading
  - [ ] a build system???
  - [ ] and a loading screen? customizable maybe just tell give the user some
    statistics about progress and they can render it themselves. sounds good to me
- [ ] benchmarks
- [ ] normal mapping in 2d and 3d
- [ ] metaballs
  - [ ] SDF in 2D?
- [ ] Svelte(fire) style magic for multiplayer. just have some kind of struct /
  macro thing that detects the difference between the state of the struct
  between frames and automatically handles that between players
  - [ ] very high trust level. could be improved. very simple though
  - [ ] so, so simple
- [ ] The... web :(
- [ ] Mobile :(
- [ ] Sound
  - [ ] 2D sound
  - [ ] Include sound
  - [ ] 3D sound
  - [ ] Not happy with sound. need to look into it more
- [X] Convert 2D Primitives to use Z-indexing so batching isnt a problem
- [-] 3D
  - [X] Camera
  - [ ] Primitives
  - [X] Drawing
  - [ ] Culling
  - [X] Importing OBJs
  - [ ] Importing more complex objects that have materials (glTF?)
  - [ ] SDFs
  - [ ] Ray tracing
  - [ ] Instanced ~draw_many~.
  - [ ] Lights
  - [X] Import from blender like godot does (why cant i be more like godot)
  - [X] add mirror BVec3 to transform3d
  - [ ] LOD
- [ ] include_(texture|object|model|sound) macros (macro crate)

* Lucas
- [X] Raycasting
- [X] Collision boxes / area 2D (AABB / circle / polygon)
- [X] Rigid bodies (rapier)
- [X] Custom polygons from shapes
- [X] physics system needs retained state. let the user retain it wherever they want. just put it all in a struct.

* Testing (slop prose)
1. Camera System (src/camera/mod.rs)
The camera transformations are complex and affect everything visual:

screen_to_world() and world_to_screen() roundtrip accuracy
zoom_at() maintaining world point under cursor
visible_bounds() calculations with various transformations
Scale, rotation, and translation combinations
Edge cases with extreme zoom levels

2. Collision Detection (src/collisions/mod.rs)
You already have good collision tests, but consider adding:

Edge cases: zero-radius circles, zero-size squares
Numerical stability with very large/small coordinates
Polygon winding order edge cases
Self-intersecting polygons
Degenerate cases (collinear points in polygons)

3. Draw Queue Z-Ordering (src/draw_queue_2d.rs)
Critical for rendering correctness:

Verify shapes draw in correct order
Test z-value management across multiple queues
Boundary conditions when z approaches limits
Z-increment behavior with many objects

4. Texture Atlas (src/textures/atlas.rs)
Complex packing logic with edge cases:

Atlas growth/reallocation correctness
Sprite retrieval after atlas resize
UV coordinate calculations
Edge cases: sprites exactly fitting remaining space
Memory efficiency with various sprite sizes

5. Material System (src/materials.rs)
Uniform handling can be fragile:

Setting and retrieving different uniform types
Uniform type mismatches
Missing required uniforms for shaders
Material cloning/copying behavior

6. Physics Integration (src/physics.rs)
Wrapper around Rapier2D but still needs tests:

Body creation and retrieval
Collider attachment
Gravity customization
Step simulation determinism
Handle validity after removals

7. Render Pipeline (src/render_pipeline.rs)
Complex state management:

Switching between render targets
Post-processing effect chains
Camera override behavior
Framebuffer attachment correctness
Resource cleanup

8. Input System (src/input.rs)
User-facing API that needs reliability:

Action binding/unbinding
Key press/release/held states
Mouse button state tracking
Action queries with unbound actions
Scroll and cursor position edge cases

9. Object3D Transformations (src/object_3d.rs)
Transform math is error-prone:

Matrix generation from SRT components
Normal matrix calculations
Mirroring behavior (especially culling mode)
Transform composition
Mark dirty/update cycles

10. Color Conversions (src/color.rs)
You have HSL/OKLCH conversions that could have edge cases:

HSL/OKLCH roundtrip accuracy
Hue rotation wrap-around (0°/360°)
Saturation/lightness clamping
Color space boundary values
Alpha channel preservation

implement shape_3d functions for generating lines, cubes, cuboids, 2d shapes in 3d space, 2d shapes always drawn facing the camera in 3d space, wireframes, a path (line) through many points
