use std::{fmt::Debug, io::Cursor};

use bevy_math::{UVec2, Vec2};
use error_union::ErrorUnion;
use glium::{
    Texture2d,
    texture::{RawImage2d, TextureCreationError},
    uniforms::{MagnifySamplerFilter, MinifySamplerFilter},
};
use image::ImageFormat;
use sge_config::get_config;
use sge_image::Image;
use sge_macros::{gen_ref_type, include_texture};
use sge_window::get_window_state;

#[derive(ErrorUnion, Debug)]
pub enum LoadTextureError {
    Image(image::error::ImageError),
    Engine(TextureCreationError),
}

pub const CLOSE_TEXTURE: TextureRef = TextureRef(0);
pub const MINIMISE_TEXTURE: TextureRef = TextureRef(1);

pub fn init() {
    init_texture_storage();
    include_texture!("../../sge_ui/assets/textures/close.png");
    include_texture!("../../sge_ui/assets/textures/minimise.png");
    log::info!("Initialized textures");
}

pub fn load_texture(bytes: &[u8], format: ImageFormat) -> Result<TextureRef, LoadTextureError> {
    Ok(SgeTexture::load_from_bytes(bytes, format)?.create())
}

gen_ref_type!(SgeTexture, TextureRef, texture);

pub struct SgeTexture {
    pub dimensions: UVec2,
    pub normalized_dimensions: Vec2,
    pub gl_texture: Texture2d,
    pub magnify_filter: MagnifySamplerFilter,
    pub minify_filter: MinifySamplerFilter,
}

impl SgeTexture {
    pub fn static_gl_texture(&'static self) -> &'static Texture2d {
        &self.gl_texture
    }

    pub fn load_from_bytes(bytes: &[u8], format: ImageFormat) -> Result<Self, LoadTextureError> {
        let image = image::load(Cursor::new(bytes), format)?.to_rgba8();
        let image_dimensions = image.dimensions();
        let image = RawImage2d::from_raw_rgba(image.into_raw(), image_dimensions);
        Ok(Self::from_raw(image)?)
    }

    pub fn new(texture: Texture2d) -> SgeTexture {
        let config = get_config();
        let dimensions = texture.dimensions().into();
        SgeTexture {
            dimensions,
            gl_texture: texture,
            normalized_dimensions: Self::create_normalized_dimensions(dimensions.x, dimensions.y),
            magnify_filter: config.default_magnify_filter,
            minify_filter: config.default_minify_filter,
        }
    }

    pub fn create_normalized_dimensions(width: u32, height: u32) -> Vec2 {
        let mut v = Vec2::new(width as f32, height as f32);
        let max = v.x.max(v.y);
        v.x /= max;
        v.y /= max;
        v
    }

    pub fn empty(width: u32, height: u32) -> Result<Self, TextureCreationError> {
        let window = get_window_state();
        Ok(Self::new(Texture2d::empty(&window.display, width, height)?))
    }

    pub fn from_engine_image(image: Image) -> Result<Self, TextureCreationError> {
        let dimensions = image.dimensions_u32().into();
        let raw = RawImage2d::from_raw_rgba(image.into_bytes(), dimensions);
        Self::from_raw(raw)
    }

    pub fn from_raw(raw: RawImage2d<'_, u8>) -> Result<Self, TextureCreationError> {
        let config = get_config();
        let window = get_window_state();
        let texture = Texture2d::with_format(
            &window.display,
            raw,
            glium::texture::UncompressedFloatFormat::U8U8U8U8,
            if config.use_mipmaps {
                glium::texture::MipmapsOption::AutoGeneratedMipmaps
            } else {
                glium::texture::MipmapsOption::NoMipmap
            },
        )?;

        Ok(SgeTexture::new(texture))
    }
}
