use std::{fmt::Debug, io::Cursor};

use glium::{
    Texture2d,
    texture::{InternalFormat, InternalFormatType, RawImage2d, TextureCreationError},
    uniforms::{MagnifySamplerFilter, MinifySamplerFilter},
};
pub use image::ImageFormat;
use sge_color::u8::ColorU8;
use sge_config::get_config;
use sge_error_union::ErrorUnion;
use sge_image::Image;
use sge_macros::gen_ref_type;
use sge_types::Area;
use sge_vectors::{UVec2, Vec2};
use sge_window::get_window_state;

#[derive(ErrorUnion, Debug)]
pub enum LoadTextureError {
    Image(image::error::ImageError),
    Engine(TextureCreationError),
    Io(std::io::Error),
    Other(&'static str),
}

pub fn init() {
    init_texture_storage();
    log::info!("Initialized textures");
}

pub fn load_texture_from_bytes_sync(
    bytes: &[u8],
    format: ImageFormat,
) -> Result<TextureRef, LoadTextureError> {
    Ok(SgeTexture::load_from_bytes(bytes, format)?.create())
}

pub fn load_texture_sync(
    path: impl AsRef<std::path::Path>,
) -> Result<TextureRef, LoadTextureError> {
    let bytes = std::fs::read(&path)?;
    let format = ImageFormat::from_path(path)?;
    load_texture_from_bytes_sync(&bytes, format)
}

gen_ref_type!(SgeTexture, TextureRef, texture);

pub struct SgeTexture {
    pub dimensions: UVec2,
    pub normalized_dimensions: Vec2,
    pub gl_texture: Texture2d,
    pub magnify_filter: MagnifySamplerFilter,
    pub minify_filter: MinifySamplerFilter,
}

impl SgeTexture {
    pub fn static_gl_texture(&'static self) -> &'static Texture2d {
        &self.gl_texture
    }

    pub fn load_from_bytes(bytes: &[u8], format: ImageFormat) -> Result<Self, LoadTextureError> {
        let image = image::load(Cursor::new(bytes), format)?.to_rgba8();
        let image_dimensions = image.dimensions();
        let image = RawImage2d::from_raw_rgba(image.into_raw(), image_dimensions);
        Ok(Self::from_raw(image)?)
    }

    pub fn new(texture: Texture2d) -> SgeTexture {
        let config = get_config();
        let dimensions = texture.dimensions().into();
        SgeTexture {
            dimensions,
            gl_texture: texture,
            normalized_dimensions: Self::create_normalized_dimensions(dimensions.x, dimensions.y),
            magnify_filter: config.default_magnify_filter,
            minify_filter: config.default_minify_filter,
        }
    }

    pub fn create_normalized_dimensions(width: u32, height: u32) -> Vec2 {
        let mut v = Vec2::new(width as f32, height as f32);
        let max = v.x.max(v.y);
        v.x /= max;
        v.y /= max;
        v
    }

    pub fn empty(width: u32, height: u32) -> Result<Self, TextureCreationError> {
        let window = get_window_state();
        Ok(Self::new(Texture2d::empty(&window.display, width, height)?))
    }

    pub fn from_engine_image(image: Image) -> Result<Self, TextureCreationError> {
        let dimensions = image.dimensions_u32().into();
        let raw = RawImage2d::from_raw_rgba(image.into_bytes(), dimensions);
        Self::from_raw(raw)
    }

    pub fn from_raw(raw: RawImage2d<'_, u8>) -> Result<Self, TextureCreationError> {
        let config = get_config();
        let window = get_window_state();
        let texture = Texture2d::with_format(
            &window.display,
            raw,
            glium::texture::UncompressedFloatFormat::U8U8U8U8,
            if config.use_mipmaps {
                glium::texture::MipmapsOption::AutoGeneratedMipmaps
            } else {
                glium::texture::MipmapsOption::NoMipmap
            },
        )?;

        Ok(SgeTexture::new(texture))
    }

    pub fn download_to_image(&self) -> Image {
        let layer = self.gl_texture.main_level().first_layer();
        let any_image = layer.into_image(None).unwrap();
        let rect = Area::new(Vec2::new(0.0, 0.0), self.dimensions.as_vec2()).to_rect();
        let format = self.gl_texture.get_internal_format().unwrap();

        match format {
            InternalFormat::FourComponents {
                ty1: InternalFormatType::Float,
                bits1: 32,
                ty2: InternalFormatType::Float,
                bits2: 32,
                ty3: InternalFormatType::Float,
                bits3: 32,
                ty4: InternalFormatType::Float,
                bits4: 32,
            } => {
                let raw_image = any_image.raw_read::<RawImage2d<f32>, f32>(&rect);
                let u8_data = raw_image
                    .data
                    .array_windows::<4>()
                    .map(|&[r, g, b, a]| ColorU8::from_rgba_f32(r, g, b, a))
                    .collect();

                let image = Image::new(
                    self.dimensions.x as usize,
                    self.dimensions.y as usize,
                    u8_data,
                );

                image
            }

            InternalFormat::ThreeComponents {
                ty1: InternalFormatType::Float,
                bits1: 32,
                ty2: InternalFormatType::Float,
                bits2: 32,
                ty3: InternalFormatType::Float,
                bits3: 32,
            } => {
                let raw_image = any_image.raw_read::<RawImage2d<f32>, f32>(&rect);
                let u8_data = raw_image
                    .data
                    .array_windows::<3>()
                    .map(|&[r, g, b]| ColorU8::from_rgba_f32(r, g, b, 1.0))
                    .collect();

                let image = Image::new(
                    self.dimensions.x as usize,
                    self.dimensions.y as usize,
                    u8_data,
                );

                image
            }

            InternalFormat::FourComponents {
                ty1: InternalFormatType::UnsignedInt,
                bits1: 8,
                ty2: InternalFormatType::UnsignedInt,
                bits2: 8,
                ty3: InternalFormatType::UnsignedInt,
                bits3: 8,
                ty4: InternalFormatType::UnsignedInt,
                bits4: 8,
            } => {
                let raw_image = any_image.raw_read::<RawImage2d<u8>, u8>(&rect);

                let image = Image::from_bytes(
                    self.dimensions.x as usize,
                    self.dimensions.y as usize,
                    raw_image.data.to_vec(),
                );

                image.unwrap()
            }

            InternalFormat::ThreeComponents {
                ty1: InternalFormatType::UnsignedInt,
                bits1: 8,
                ty2: InternalFormatType::UnsignedInt,
                bits2: 8,
                ty3: InternalFormatType::UnsignedInt,
                bits3: 8,
            } => {
                let raw_image = any_image.raw_read::<RawImage2d<u8>, u8>(&rect);
                let u8_data = raw_image
                    .data
                    .array_windows::<3>()
                    .map(|&[r, g, b]| ColorU8::from_rgba(r, g, b, 255))
                    .collect();

                let image = Image::new(
                    self.dimensions.x as usize,
                    self.dimensions.y as usize,
                    u8_data,
                );

                image
            }

            _ => panic!("Unsupported texture format"),
        }
    }
}

pub fn num_registered_textures() -> usize {
    get_texture_state().len()
}
